language: rust
sudo: false
matrix:
  include:
      # These are the latest Rust versions
    - os: linux
      dist: trusty
      sudo: required
      rust: stable
      git:
        submodules: false
      addons:
        apt:
          packages: libudev-dev file cmake
      cache: cargo
      script:
        - travis_wait 60 cargo build --release --features final
      before_deploy:
        - sh scripts/travis/deploy.sh
      deploy:
        provider: releases
        api_key:
          secure: TFVZi6OZIm7YbUO7MXnEOF3kxuDwInz/e1wpenQiq4niZBEM85xVA2EvLdk8nICVz69xivXBhXaDY/Q4eQz5890tOeh9Z5eBPluNixgDF2jmGHyryD6EGgK4ZsNJPaVqJZqcpTZi43pyStFO0Gh4CCoIAOC7yQH3h/UcjLoJGirjVUXFvnRdVEX+ovr5d2CU+e5J8dtgJ0DP7Fmq2qWj/w6O7OcNNQaCDgUOPhWSuFs5QDXFNh9fSsRhuXmhfwgjH9d87E7TW66Xv+hDMqrRIY1hRuHuBuYbmx1gnPM2rXQmP7QsLT53Grkd2dSUbb6ELII8L/PORa5GgwIpwF1t3qdO3nU2X0FI0OJd1s4DvMfcwOB0ZRD7vy8KL2cErgb2g2yltnzIoYCWEjOaDBXYMkr6OH49wRsbq/SF6uF1RsdEMWTUy5wq492miBqzy6lCAUQBmLnTUDdM30RJ92Vog2f+yWARnkOV+LYDRtOprCywyI2f7XfcRTlt/FdDo9RLaODmtohHpv7Zbpo5OFUcvA7qFKIVXQ9gvCaTPoX1JIau8ZqyRy5nBDpVz9KOtnH7MfaL8ZzLCeTVfaavXIXEXEik8sove4T/Bd4nQMLes3Yxwyb1l4sjGgK6cNX8aD9twcqx2RGdwvvHiw6kBILrRyow3L2DoUmpgCSuDpzIrtk=
        file: reosc-$TRAVIS_OS_NAME-$TRAVIS_TAG.*
        file_glob: true
        draft: true
        on:
          repo: REOSC/reosc-node
          tags: true
        skip_cleanup: true
        tag_name: "$TRAVIS_TAG"
