[package]
description = "Parity Updater Service."
name = "parity-updater"
version = "1.12.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
keccak-hash = "0.1"
lazy_static = "1.0"
log = "0.4"
ethabi = "6.0"
ethabi-derive = "6.0"
ethabi-contract = "6.0"
target_info = "0.1"
semver = "0.9"
ethcore = { path = "../ethcore" }
parity-bytes = "0.1"
ethcore-sync = { path = "../ethcore/sync" }
ethereum-types = "0.4"
parking_lot = "0.6"
parity-hash-fetch = { path = "../hash-fetch" }
parity-version = { path = "../util/version" }
parity-path = "0.1"
rand = "0.4"

[dev-dependencies]
ethcore = { path = "../ethcore", features = ["test-helpers"] }
tempdir = "0.3"
matches = "0.1"

[features]
# hardcode version number 1.3.7 of parity to force an update
# in order to manually test that parity fall-over to the local version
# in case of invalid or deprecated command line arguments are entered
test-updater = []
